gems:
  - jekyll-sitemap
  - md2gemini

kiss: https://mcpcpc.com/k1ss
wiki: https://mcpcpc.com/k1ss/wiki
blog: https://mcpcpc.com/k1ss/blog
news: https://mcpcpc.com/k1ss/news
git:  https://github.com/kiss-community
user: https://github/com
